# https://taskfile.dev

version: '3'

vars:

tasks:
  default: # this is run if no task is specified
    deps: [revealjs]

  beamer:
    desc: Build Beamer PDF slides with Pandoc
    cmds:
      - pandoc -t beamer *.md > body.tex
      - sed -i '/\\tightlist/d' body.tex
      - pdflatex --interaction=nonstodmode slides.tex
    silent: true

  revealjs:
    desc: Build revealjs HTML slides with Pandoc
    cmds:
      - |
        pandoc --from=markdown -t revealjs -s -o slides.html *.md
        # --css=mytheme.css
        # -V mainfont=Futura -V fontsize=14pt
        # -V theme=night \
    sources:
      - '*.md'
    generates:
      - slides.html
    method: timestamp # instead of default checksum
    silent: true

  gotask:
    desc: Set up Task (Taskfile/Go-Task, make alternative)
    cmds:
      - |
        sudo snap install task
