version: "3"

vars:
  MYVAR1: derp
  MYVAR2: schlerp
  MYVAR3: {sh: whoami} # (ba)sh command substitution
  MYVAR4: "He was just like '{{.MYVAR1}}'!" # Variable expansion
  CURRENT_TIME: '{{now | date "2006-01-02"}}' # Use Go template functions

tasks:
  noway: # Task name
    desc: "Hilarious story bro!"
    cmds:
    - echo {{.MYVAR4}}
  whoami:
    desc: "Tell me who I am!"
    cmds:
    - echo {{.MYVAR3}}
    silent: true # Silence output of task name and cmds
  whatdate:
    desc: "Tell me the date!"
    cmds:
    - echo Today is the {{.CURRENT_TIME}}
    silent: true # Silence output of task name and cmds
