# https://taskfile.dev

version: '3'

vars:

tasks:
  default: # this is run if no task is specified
    cmds:
      - task: revealjs_build
      - task: revealjs_reload

  beamer:
    desc: Build Beamer PDF slides with Pandoc
    cmds:
      - pandoc -t beamer *.md > body.tex
      - sed -i '/\\tightlist/d' body.tex
      - pdflatex --interaction=nonstodmode slides.tex
    silent: true

  revealjs_build:
    desc: Build revealjs HTML slides with Pandoc
    cmds:
      - |
        pandoc --from=markdown -t revealjs --slide-level 2 -s -o slides.html presentation.md \
        --verbose \
        -F mermaid-filter \
        -L revealjs-codeblock.lua \
        --css rug.css
        [[ -f mermaid-filter.err ]] && rm mermaid-filter.err
    sources:
      - '*.md'
      - '*.css'
      - Taskfile.yml
    generates:
      - slides.html
    method: timestamp # instead of default checksum
    silent: true

  revealjs_reload:
    desc: Reload browser windows with revealjs presentation
    cmds:
      - ./reload_browser.sh "Gitlab - Issues, Boards, Kanban"
    silent:
      true

  gotask:
    desc: Set up Task (Taskfile/Go-Task, make alternative)
    cmds:
      - |
        sudo snap install task
