# See https://alacritty.org/config-alacritty.html
# and https://wiki.archlinux.org/title/Alacritty

import = [
    "~/.config/alacritty/themes/catppuccin-macchiato.toml"
]

[font]
size = 10

[font.normal]
family = "JetBrainsMonoNL Nerd Font Mono"
style = "Regular"

[font.bold]
family = "JetBrainsMonoNL Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMonoNL Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMonoNL Nerd Font Mono"
style = "Italic"

